sudo: false
language: node_js
node_js:
  - "4.0"
  - "5.0"
  - "6.13"
  - "8.10"
  - "stable"

# Make sure we have new NPM.
before_install:
  - if [[ "`node --version`" = v0* ]] || [[ "`node --version`" = v4* ]]; then npm install -g npm@latest-3; fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli

script:
  - grunt
  - ./integration-tests.sh
